### ISSUE TITLE
Bankroll Graphs

### ISSUE THREAD

**Issue by aautem** [AMess33/PokerRoll#14]
Bankroll page displays one graph that can be toggled between two different views:

1. bankroll change over time
2. +/- of all sessions with 0 being the starting point based on timeframe you want to view (month/ 6 months/ 12 months/ ytd)

Charting library options:
- https://recharts.org/en-US/examples/SimpleLineChart
- https://nivo.rocks/line/
- https://react-chartjs-2.js.org/examples/line-chart

**Comment by aautem** [comment]
Graph functionality has been implemented, ready to clean up and add real data.

**Comment by AMess33** [comment]
real data added and graph is working as intended, further tweaks during styling may be needed
